name: periodnpregnancycalender
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0-107.0.dev <4.0.0"

dependencies:
  calendar_date_picker2: null
  connectivity_plus: ^6.0.3
  custom_date_range_picker: ^1.0.10
  d_chart: ^2.6.5
  device_info_plus: ^10.1.2
  device_preview: ^1.2.0
  dotted_border: ^2.1.0
  firebase_analytics: ^11.2.1
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.1+2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: null
  flutter_secure_storage: ^9.2.2
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.0
  font_awesome_flutter: ^10.7.0
  get: null
  get_storage: ^2.1.1
  html: ^0.15.4
  http: ^1.1.2
  iconsax: null
  intl: ^0.19.0
  like_button: ^2.0.5
  logger: ^2.3.0
  lottie: ^3.1.2
  numberpicker: ^2.1.2
  path: ^1.9.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pinput: ^3.0.1
  readmore: ^3.0.0
  sqflite: ^2.3.3+1
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_charts: ^24.2.8
  syncfusion_flutter_datepicker: ^24.1.44
  table_calendar: ^3.1.1
  timezone: ^0.9.4
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/image/
    - assets/image/baby_comparison/
    - assets/image/fetal_development/
    - assets/icon/
    - assets/lottie/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/font-family/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/font-family/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/font-family/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/font-family/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/font-family/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/font-family/PlusJakartaSans-ExtraBold.ttf
          weight: 800
