name: periodnpregnancycalender
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0-107.0.dev <4.0.0"

dependencies:
  android_alarm_manager_plus: ^3.0.4
  calendar_date_picker2: null
  cherry_toast: ^1.10.1
  cupertino_icons: null
  custom_date_range_picker: ^1.0.10
  d_chart: ^2.6.5
  dio: ^5.4.0
  dotted_border: ^2.1.0
  filter_list: ^1.0.2
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.1.0
  flutter_neat_and_clean_calendar: ^0.3.14+32
  flutter_screenutil: null
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.0
  font_awesome_flutter: ^10.7.0
  get: null
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.1.2
  iconsax: null
  like_button: ^2.0.5
  numberpicker: ^2.1.2
  path_provider: ^2.1.1
  photo_view: ^0.15.0
  pinput: ^3.0.1
  scrollable_clean_calendar: ^1.4.1
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_charts: ^24.2.8
  syncfusion_flutter_datepicker: ^24.1.44
  table_calendar: ^3.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    # - assets/image/chinese chart.jpg
