// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1uKGd4rhzdSJptOgT0eRghq7GcmZB2fI',
    appId: '1:724266695440:web:27ddda9b3b67ea81b68395',
    messagingSenderId: '724266695440',
    projectId: 'menstrual-calendar-n-pregnancy',
    authDomain: 'menstrual-calendar-n-pregnancy.firebaseapp.com',
    storageBucket: 'menstrual-calendar-n-pregnancy.appspot.com',
    measurementId: 'G-0578B50R2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBPIBeR19p6RfRezj5FlYzEfY9CXVtCjs',
    appId: '1:724266695440:android:b5a4728efb19dbbab68395',
    messagingSenderId: '724266695440',
    projectId: 'menstrual-calendar-n-pregnancy',
    storageBucket: 'menstrual-calendar-n-pregnancy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByXVnOjzOYobm9h6XqZCSu6Eh2bemCn24',
    appId: '1:724266695440:ios:e951274daba15b51b68395',
    messagingSenderId: '724266695440',
    projectId: 'menstrual-calendar-n-pregnancy',
    storageBucket: 'menstrual-calendar-n-pregnancy.appspot.com',
    iosBundleId: 'com.medhikobiraja.periodnpregnancycalender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByXVnOjzOYobm9h6XqZCSu6Eh2bemCn24',
    appId: '1:724266695440:ios:e951274daba15b51b68395',
    messagingSenderId: '724266695440',
    projectId: 'menstrual-calendar-n-pregnancy',
    storageBucket: 'menstrual-calendar-n-pregnancy.appspot.com',
    iosBundleId: 'com.medhikobiraja.periodnpregnancycalender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1uKGd4rhzdSJptOgT0eRghq7GcmZB2fI',
    appId: '1:724266695440:web:67f0dda47985aab7b68395',
    messagingSenderId: '724266695440',
    projectId: 'menstrual-calendar-n-pregnancy',
    authDomain: 'menstrual-calendar-n-pregnancy.firebaseapp.com',
    storageBucket: 'menstrual-calendar-n-pregnancy.appspot.com',
    measurementId: 'G-5DF3TTS4X2',
  );
}
